language: python
python:
  - 2.7

# command to install dependencies
install:
  - pip install -v Flask==0.10.1
  - pip install -r requirements.txt

before_script: sudo redis-server /etc/redis/redis.conf --port 6379

script: python run.py test
